-- Phase 1: Clean existing data for fresh start
TRUNCATE TABLE public.oracle_logs CASCADE;
TRUNCATE TABLE public.messages CASCADE;
TRUNCATE TABLE public.mentor_requests CASCADE;
TRUNCATE TABLE public.builder_assignments CASCADE;
TRUNCATE TABLE public.updates CASCADE;
TRUNCATE TABLE public.members CASCADE;
TRUNCATE TABLE public.access_codes CASCADE;
TRUNCATE TABLE public.team_status CASCADE;
TRUNCATE TABLE public.profiles CASCADE;
TRUNCATE TABLE public.teams CASCADE;  
TRUNCATE TABLE public.documents CASCADE;
TRUNCATE TABLE public.role_assignments CASCADE;
TRUNCATE TABLE public.builder_onboarding CASCADE;
TRUNCATE TABLE public.mentor_profiles CASCADE;
TRUNCATE TABLE public.events CASCADE;
TRUNCATE TABLE public.bot_commands_log CASCADE;

-- Phase 2: Drop all RLS policies that reference user_role enum
DROP POLICY IF EXISTS "Users can view their own messages" ON public.messages;
DROP POLICY IF EXISTS "Users can send messages as themselves" ON public.messages;  
DROP POLICY IF EXISTS "Users can mark their received messages as read" ON public.messages;
DROP POLICY IF EXISTS "Leads can view all messages for moderation" ON public.messages;
DROP POLICY IF EXISTS "Leads can manage messages for moderation" ON public.messages;
DROP POLICY IF EXISTS "Leads can manage all access codes" ON public.access_codes;
DROP POLICY IF EXISTS "Authenticated users can read access codes for validation" ON public.access_codes;
DROP POLICY IF EXISTS "Users can update their own access codes" ON public.access_codes;
DROP POLICY IF EXISTS "Leads can manage members" ON public.members;
DROP POLICY IF EXISTS "Users can view members of their team" ON public.members;
DROP POLICY IF EXISTS "Users can insert member records during onboarding" ON public.members;
DROP POLICY IF EXISTS "Users can update member records they create" ON public.members;
DROP POLICY IF EXISTS "Only leads can manage role assignments" ON public.role_assignments;
DROP POLICY IF EXISTS "Leads can manage all teams" ON public.teams;
DROP POLICY IF EXISTS "Leads can manage all updates" ON public.updates;
DROP POLICY IF EXISTS "Leads can manage all builder assignments" ON public.builder_assignments;
DROP POLICY IF EXISTS "Leads can manage all mentor requests" ON public.mentor_requests;
DROP POLICY IF EXISTS "Leads can manage all team status" ON public.team_status;
DROP POLICY IF EXISTS "Leads can manage all builder onboarding data" ON public.builder_onboarding;
DROP POLICY IF EXISTS "Users can view their own oracle logs" ON public.oracle_logs;
DROP POLICY IF EXISTS "Users can insert their own oracle logs" ON public.oracle_logs;
DROP POLICY IF EXISTS "Users can view their own bot command logs" ON public.bot_commands_log;
DROP POLICY IF EXISTS "Bot can insert command logs" ON public.bot_commands_log;